name: 'Loxcan'
author: 'Naoki Ikeguchi'
description: 'Universal Lock File Scanner for Git.'
branding:
  icon: 'search'
  color: 'yellow'
inputs:
  report_enabled:
    required: true
    description: 'Reports to GitHub pull request only if this input is "true".'
    default: '${{ github.event.repository.owner.id == github.event.pull_request.head.user.id }}'
  owner:
    required: true
    description: 'The owner (organization) of the repository.'
    default: ${{ github.event.repository.owner.login }}
  repo:
    required: true
    description: 'The name of the repository.'
    default: ${{ github.event.repository.name }}
  base:
    required: true
    description: 'The base branch of the pull request.'
    default: ${{ github.event.pull_request.base.ref }}
  pull_number:
    required: true
    description: 'The number of a pull request to add a comment.'
    default: ${{ github.event.pull_request.number }}
  token:
    required: true
    description: 'An OAuth token to access to the repository as a bot.'
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'Dockerfile'
