name: 'Loxcan'
author: 'Naoki Ikeguchi'
description: 'Universal Lock File Scanner for Git.'
branding:
  icon: 'search'
  color: 'yellow'
inputs:
  owner:
    required: true
    description: 'The owner (organization) of the repository.'
  repo:
    required: true
    description: 'The name of the repository.'
  base:
    required: true
    description: 'The base branch of the pull request.'
  issue_number:
    required: true
    description: 'The number of a issue or pull request to add a comment.'
runs:
  using: 'docker'
  image: 'Dockerfile'
