#!/usr/bin/env sh

# shellcheck disable=SC2034
LOXCAN_REPORTER_GITHUB="1"
LOXCAN_REPORTER_GITHUB_OWNER="${INPUT_OWNER}"
LOXCAN_REPORTER_GITHUB_REPO="${INPUT_REPO}"
LOXCAN_REPORTER_GITHUB_ISSUE_NUMBER="${INPUT_ISSUE-NUMBER}"
LOXCAN_REPORTER_GITHUB_TOKEN="${INPUT_TOKEN}"

BRANCH_BASE="${INPUT_BASE}"
BRANCH_HEAD="${INPUT_HEAD}"

/app/bin/loxcan "${BRANCH_BASE}" "${BRANCH_HEAD}"
